spring:
  cloud:
    gateway:
      routes:
        - id: user           # 路由的唯一标识
          uri: http://localhost:8081  # 如果断言成功，将要转发去的地址
          order: 0                    # 优先级，越小优先级越高
          predicates: # 断言，满足所有断言，才会进行转发
            - Path=/user/**        # 注意：这是使用= 不是：
          filters:
            - StripPrefix=1 # #转发请求时去掉1级前缀，去掉端口后的第一个节点，这里是client
---
spring:
  application:
    name: ES-Spring-Stu
  # 应用名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    port: 6379
    host: localhost
info-bridge-feign:
  user-service-url: http://localhost:8081