server:
  port: 8080
logging:
  level:
    com.infobridge.bridge.fegin.UserService: DEBUG
  # DataSource Config
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/bridge
    username: root
    password: test
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql

  redis:
    host: localhost
    port: 6379
#    password: test
redis:
  key:
    user:
      userLocationKey: geo:nearby
      userMoodKey: geo:mood
info-bridge-feign:
  user-service-url: http://localhost:8081


AI:
  zhipu:
    apiKey:
  tongyi:
    apiKey: